development:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 4KAPnt76m
    password: 64Kcb8834Z8f6yEm
  freshbook:
    login: vtn-billing.freshbooks.com
    password: f26f576d8a60a60324e139b575a9a8fa

production:
  paypal:
    login: rjohnston_api1.colosses.com
    password: BAT9ZE4X6EAXU46Q
    signature: ABwmBAIEJPBtRUnk9k-iMfCgx5nrAMrnY9L1hhyI4NzMx5OtLtkrsOmr
  authorizenet:
    login: 29U2GgeyC7
    password: 4A62xU5m63mQ7vTH
  freshbook:
    login: vtn-billing.freshbooks.com
    password: f26f576d8a60a60324e139b575a9a8fa

staging:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 93W5Ghw3j
    password: 5G3b7ppn4T22Ja3S
  freshbook:
    login: vtn-billing.freshbooks.com
    password: f26f576d8a60a60324e139b575a9a8fa

test:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 93W5Ghw3j
    password: 5G3b7ppn4T22Ja3S

sandbox:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 93W5Ghw3j
    password: 5G3b7ppn4T22Ja3S
